version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: biblioteca
      POSTGRES_USER: biblioteca_user
      POSTGRES_PASSWORD: biblioteca_pass
    ports:
      - "25433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - biblioteca_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U biblioteca_user -d biblioteca"]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.29
    container_name: liquibase_liquibase
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./Databases_jesus_ariel:/liquibase/changelog
    working_dir: /liquibase/changelog
    command: --defaults-file=liquibase.properties update
    networks:
      - biblioteca_net

  backend:
    build:
      context: ./backend_jesus_ariel
    container_name: backend
    depends_on:
      postgres:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/biblioteca
      SPRING_DATASOURCE_USERNAME: biblioteca_user
      SPRING_DATASOURCE_PASSWORD: biblioteca_pass
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - biblioteca_net

  frontend:
    build:
      context: ./Front-end_jesus_ariel
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - biblioteca_net

networks:
  biblioteca_net:

volumes:
  postgres_data:
