CREATE TABLE usuarios (
    id BIGSERIAL PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    correo VARCHAR(160) NOT NULL UNIQUE,
    telefono VARCHAR(40),
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
